# Generated by Django 4.2 on 2025-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieinfo_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='description',
            field=models.TextField(default='good'),
        ),
    ]
