# Generated by Django 4.2 on 2025-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_delete_director_alter_movieinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
