# Generated by Django 4.2 on 2025-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movieinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='description',
            field=models.TextField(blank=True, default='good', null=True),
        ),
    ]
